# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    container_name: issues-mongo-db
    ports:
      - 27017:27017
    volumes:
      - "./docker/volumes/mongo/data:/data"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: issues